name: Scan de Sécurité (Secrets)

# Ce pipeline s'active à chaque fois qu'on envoie du code sur GitHub
on: [push, pull_request]

jobs:
  chasse-aux-secrets:
    runs-on: ubuntu-latest
    steps:
      # 1. Le robot télécharge votre code
      - name: Récupérer le code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Le robot lance TruffleHog pour analyser le code
      - name: Lancer TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ""
          head: ${{ github.ref_name }}